### ISSUE TITLE
`language-markdown` package support

### ISSUE THREAD

**Issue by rkpatel33** [burodepeper/mark-embedded-code#1]
(Hey David, Rishi here)

This works great, thanks for putting the time into this. I noticed that this works with `language-gfm`, but not with `language-markdown`. Can this be added easily, or is there a reason it's not?

Thanks.

**Comment by burodepeper** [comment]
Actually, it should only work with `language-markdown`, and not with `language-gfm`. You could try fixing it yourself btw. [This](https://github.com/burodepeper/mark-code-blocks/blob/master/lib/main.js#L7-L15) is how the scopes for a grammar are defined.

**Comment by rkpatel33** [comment]
I apologies, this is working, not sure why it did not show up right away. Sorry about that. Thanks for the quick response.

**Comment by burodepeper** [comment]
No problem!
Let me know how it "feels". I used it for a while, but the performance
seems to take quite a hit when I was editing one of the marked blocks.
